// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: place-srv.proto

package place

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Place service

func NewPlaceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Place service

type PlaceService interface {
	// 获取有电影院的地点
	HotCitiesByCinema(ctx context.Context, in *HotCitiesByCinemaReq, opts ...client.CallOption) (*HotCitiesByCinemaRep, error)
}

type placeService struct {
	c    client.Client
	name string
}

func NewPlaceService(name string, c client.Client) PlaceService {
	return &placeService{
		c:    c,
		name: name,
	}
}

func (c *placeService) HotCitiesByCinema(ctx context.Context, in *HotCitiesByCinemaReq, opts ...client.CallOption) (*HotCitiesByCinemaRep, error) {
	req := c.c.NewRequest(c.name, "Place.HotCitiesByCinema", in)
	out := new(HotCitiesByCinemaRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Place service

type PlaceHandler interface {
	// 获取有电影院的地点
	HotCitiesByCinema(context.Context, *HotCitiesByCinemaReq, *HotCitiesByCinemaRep) error
}

func RegisterPlaceHandler(s server.Server, hdlr PlaceHandler, opts ...server.HandlerOption) error {
	type place interface {
		HotCitiesByCinema(ctx context.Context, in *HotCitiesByCinemaReq, out *HotCitiesByCinemaRep) error
	}
	type Place struct {
		place
	}
	h := &placeHandler{hdlr}
	return s.Handle(s.NewHandler(&Place{h}, opts...))
}

type placeHandler struct {
	PlaceHandler
}

func (h *placeHandler) HotCitiesByCinema(ctx context.Context, in *HotCitiesByCinemaReq, out *HotCitiesByCinemaRep) error {
	return h.PlaceHandler.HotCitiesByCinema(ctx, in, out)
}
