// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"demo-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取id
				Method:  http.MethodPost,
				Path:    "/demo/id",
				Handler: demoHandler(serverCtx),
			},
		},
	)
}
