// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gzsUserFieldNames          = builder.RawFieldNames(&GzsUser{})
	gzsUserRows                = strings.Join(gzsUserFieldNames, ",")
	gzsUserRowsExpectAutoSet   = strings.Join(stringx.Remove(gzsUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gzsUserRowsWithPlaceHolder = strings.Join(stringx.Remove(gzsUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGoZeroShiroGzsUserIdPrefix = "cache:goZeroShiro:gzsUser:id:"
)

type (
	gzsUserModel interface {
		Insert(ctx context.Context, data *GzsUser) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*GzsUser, error)
		Update(ctx context.Context, data *GzsUser) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultGzsUserModel struct {
		sqlc.CachedConn
		table string
	}

	GzsUser struct {
		Id   uint64         `db:"id"`
		Name sql.NullString `db:"name"`
	}
)

func newGzsUserModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGzsUserModel {
	return &defaultGzsUserModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`gzs_user`",
	}
}

func (m *defaultGzsUserModel) Delete(ctx context.Context, id uint64) error {
	goZeroShiroGzsUserIdKey := fmt.Sprintf("%s%v", cacheGoZeroShiroGzsUserIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, goZeroShiroGzsUserIdKey)
	return err
}

func (m *defaultGzsUserModel) FindOne(ctx context.Context, id uint64) (*GzsUser, error) {
	goZeroShiroGzsUserIdKey := fmt.Sprintf("%s%v", cacheGoZeroShiroGzsUserIdPrefix, id)
	var resp GzsUser
	err := m.QueryRowCtx(ctx, &resp, goZeroShiroGzsUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gzsUserRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGzsUserModel) Insert(ctx context.Context, data *GzsUser) (sql.Result, error) {
	goZeroShiroGzsUserIdKey := fmt.Sprintf("%s%v", cacheGoZeroShiroGzsUserIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?)", m.table, gzsUserRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name)
	}, goZeroShiroGzsUserIdKey)
	return ret, err
}

func (m *defaultGzsUserModel) Update(ctx context.Context, data *GzsUser) error {
	goZeroShiroGzsUserIdKey := fmt.Sprintf("%s%v", cacheGoZeroShiroGzsUserIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gzsUserRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Id)
	}, goZeroShiroGzsUserIdKey)
	return err
}

func (m *defaultGzsUserModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGoZeroShiroGzsUserIdPrefix, primary)
}

func (m *defaultGzsUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gzsUserRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGzsUserModel) tableName() string {
	return m.table
}
