// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cinema/getCinemaMessageByCid": {
            "post": {
                "description": "正在销售的影片信息和影院信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影厅中心"
                ],
                "summary": "正在销售的影片信息和影院信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "影院id",
                        "name": "cinemaId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/cinema/getMovieHallByMHId": {
            "post": {
                "description": "获取影厅座位表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影厅中心"
                ],
                "summary": "获取影厅座位表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "影厅id",
                        "name": "mhId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/cinema/locationCinema": {
            "post": {
                "description": "根据location_id 获取影院",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影厅中心"
                ],
                "summary": "获取影院",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "定位id",
                        "name": "locationId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/comment/deleteComment": {
            "post": {
                "description": "删除评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论中心"
                ],
                "summary": "删除评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "评论id",
                        "name": "commentID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/comment/hotComment": {
            "post": {
                "description": "获取评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论中心"
                ],
                "summary": "获取评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "影片id",
                        "name": "movieId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/comment/makeComment": {
            "post": {
                "description": "评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论中心"
                ],
                "summary": "评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "影片id",
                        "name": "movieId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标题",
                        "name": "title",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "内容",
                        "name": "headImg",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "昵称",
                        "name": "nickname",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/comment/myComments": {
            "post": {
                "description": "我的评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论中心"
                ],
                "summary": "我的评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/comment/upNumComment": {
            "post": {
                "description": "评论点赞",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论中心"
                ],
                "summary": "评论点赞",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "评论id",
                        "name": "commentID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/film/getFilmsByCidADay": {
            "post": {
                "description": "获取正在销售的影片信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影片中心"
                ],
                "summary": "获取正在销售的影片信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "影厅id",
                        "name": "cinemaId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "影片id",
                        "name": "filmId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "时间 0：今天 1：明天 2：后天",
                        "name": "dayNum",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/film/hotPlayMovies": {
            "get": {
                "description": "搜索--暂时写死",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影片中心"
                ],
                "summary": "搜索",
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/film/imageAll": {
            "post": {
                "description": "剧照",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影片中心"
                ],
                "summary": "剧照",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "影片id",
                        "name": "movieId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/film/locationMovies": {
            "get": {
                "description": "上映的影片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影片中心"
                ],
                "summary": "上映的影片",
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/film/movieComingNew": {
            "post": {
                "description": "即将上映的影片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影片中心"
                ],
                "summary": "即将上映的影片",
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/film/movieCreditsWithTypes": {
            "post": {
                "description": "获取影片导演演员",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影片中心"
                ],
                "summary": "获取影片导演演员",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "影片id",
                        "name": "movieId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/film/movieDetail": {
            "post": {
                "description": "影片详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影片中心"
                ],
                "summary": "影片详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "影片id",
                        "name": "movieId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/order/getOrderMessage": {
            "post": {
                "description": "订单详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影片中心"
                ],
                "summary": "订单详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/order/lookAlreadyOrders": {
            "post": {
                "description": "查看看过的电影",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影片中心"
                ],
                "summary": "查看看过的电影",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/order/lookOrders": {
            "post": {
                "description": "查看所有(订单)电影票",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影片中心"
                ],
                "summary": "查看所有(订单)电影票",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/order/orderComment": {
            "post": {
                "description": "订单评分",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影片中心"
                ],
                "summary": "订单评分",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分数",
                        "name": "score",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/order/payOrder": {
            "post": {
                "description": "付款并更新用户手机",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影片中心"
                ],
                "summary": "付款并更新用户手机",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/order/ticket": {
            "post": {
                "description": "选取影厅座位并生成订单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影片中心"
                ],
                "summary": "选取影厅座位并生成订单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "影厅id",
                        "name": "mhId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "影片id",
                        "name": "filmId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "座位x",
                        "name": "x",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "座位y",
                        "name": "y",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "startTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "endTime",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/order/wantTicket": {
            "post": {
                "description": "记录想看的电影",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "影片中心"
                ],
                "summary": "记录想看的电影",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "影片id",
                        "name": "filmId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/user/loginAccount": {
            "post": {
                "description": "用户登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户中心"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/user/registAccount": {
            "post": {
                "description": "用户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户中心"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "账号",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/user/updateUserProfile": {
            "post": {
                "description": "用户更新",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户中心"
                ],
                "summary": "用户更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "账号",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "手机",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/user/wantScore": {
            "post": {
                "description": "评分（需要下单后才能评分）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户中心"
                ],
                "summary": "电影评分",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "电影id",
                        "name": "movieId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "1": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "影院订票系统",
	Description:      "影院订票系统.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
