// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user-srv.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	InsertUser(ctx context.Context, in *InsertUserReq, opts ...client.CallOption) (*InsertUserRep, error)
	DeletetUser(ctx context.Context, in *DeletetUserReq, opts ...client.CallOption) (*DeletetUserRep, error)
	SelectUser(ctx context.Context, in *SelectUserReq, opts ...client.CallOption) (*SelectUserRep, error)
	UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...client.CallOption) (*UpdateUserRep, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) InsertUser(ctx context.Context, in *InsertUserReq, opts ...client.CallOption) (*InsertUserRep, error) {
	req := c.c.NewRequest(c.name, "UserService.InsertUser", in)
	out := new(InsertUserRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) DeletetUser(ctx context.Context, in *DeletetUserReq, opts ...client.CallOption) (*DeletetUserRep, error) {
	req := c.c.NewRequest(c.name, "UserService.DeletetUser", in)
	out := new(DeletetUserRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SelectUser(ctx context.Context, in *SelectUserReq, opts ...client.CallOption) (*SelectUserRep, error) {
	req := c.c.NewRequest(c.name, "UserService.SelectUser", in)
	out := new(SelectUserRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...client.CallOption) (*UpdateUserRep, error) {
	req := c.c.NewRequest(c.name, "UserService.UpdateUser", in)
	out := new(UpdateUserRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	InsertUser(context.Context, *InsertUserReq, *InsertUserRep) error
	DeletetUser(context.Context, *DeletetUserReq, *DeletetUserRep) error
	SelectUser(context.Context, *SelectUserReq, *SelectUserRep) error
	UpdateUser(context.Context, *UpdateUserReq, *UpdateUserRep) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		InsertUser(ctx context.Context, in *InsertUserReq, out *InsertUserRep) error
		DeletetUser(ctx context.Context, in *DeletetUserReq, out *DeletetUserRep) error
		SelectUser(ctx context.Context, in *SelectUserReq, out *SelectUserRep) error
		UpdateUser(ctx context.Context, in *UpdateUserReq, out *UpdateUserRep) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) InsertUser(ctx context.Context, in *InsertUserReq, out *InsertUserRep) error {
	return h.UserServiceHandler.InsertUser(ctx, in, out)
}

func (h *userServiceHandler) DeletetUser(ctx context.Context, in *DeletetUserReq, out *DeletetUserRep) error {
	return h.UserServiceHandler.DeletetUser(ctx, in, out)
}

func (h *userServiceHandler) SelectUser(ctx context.Context, in *SelectUserReq, out *SelectUserRep) error {
	return h.UserServiceHandler.SelectUser(ctx, in, out)
}

func (h *userServiceHandler) UpdateUser(ctx context.Context, in *UpdateUserReq, out *UpdateUserRep) error {
	return h.UserServiceHandler.UpdateUser(ctx, in, out)
}
