// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user-srv.proto

package usersrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserSrv service

func NewUserSrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserSrv service

type UserSrvService interface {
	InsertUser(ctx context.Context, in *InsertUserReq, opts ...client.CallOption) (*InsertUserResp, error)
	DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...client.CallOption) (*DeleteUserResp, error)
	SelectUser(ctx context.Context, in *SelectUserReq, opts ...client.CallOption) (*SelectUserResp, error)
	UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...client.CallOption) (*UpdateUserResp, error)
}

type userSrvService struct {
	c    client.Client
	name string
}

func NewUserSrvService(name string, c client.Client) UserSrvService {
	return &userSrvService{
		c:    c,
		name: name,
	}
}

func (c *userSrvService) InsertUser(ctx context.Context, in *InsertUserReq, opts ...client.CallOption) (*InsertUserResp, error) {
	req := c.c.NewRequest(c.name, "UserSrv.InsertUser", in)
	out := new(InsertUserResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvService) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...client.CallOption) (*DeleteUserResp, error) {
	req := c.c.NewRequest(c.name, "UserSrv.DeleteUser", in)
	out := new(DeleteUserResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvService) SelectUser(ctx context.Context, in *SelectUserReq, opts ...client.CallOption) (*SelectUserResp, error) {
	req := c.c.NewRequest(c.name, "UserSrv.SelectUser", in)
	out := new(SelectUserResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvService) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...client.CallOption) (*UpdateUserResp, error) {
	req := c.c.NewRequest(c.name, "UserSrv.UpdateUser", in)
	out := new(UpdateUserResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserSrv service

type UserSrvHandler interface {
	InsertUser(context.Context, *InsertUserReq, *InsertUserResp) error
	DeleteUser(context.Context, *DeleteUserReq, *DeleteUserResp) error
	SelectUser(context.Context, *SelectUserReq, *SelectUserResp) error
	UpdateUser(context.Context, *UpdateUserReq, *UpdateUserResp) error
}

func RegisterUserSrvHandler(s server.Server, hdlr UserSrvHandler, opts ...server.HandlerOption) error {
	type userSrv interface {
		InsertUser(ctx context.Context, in *InsertUserReq, out *InsertUserResp) error
		DeleteUser(ctx context.Context, in *DeleteUserReq, out *DeleteUserResp) error
		SelectUser(ctx context.Context, in *SelectUserReq, out *SelectUserResp) error
		UpdateUser(ctx context.Context, in *UpdateUserReq, out *UpdateUserResp) error
	}
	type UserSrv struct {
		userSrv
	}
	h := &userSrvHandler{hdlr}
	return s.Handle(s.NewHandler(&UserSrv{h}, opts...))
}

type userSrvHandler struct {
	UserSrvHandler
}

func (h *userSrvHandler) InsertUser(ctx context.Context, in *InsertUserReq, out *InsertUserResp) error {
	return h.UserSrvHandler.InsertUser(ctx, in, out)
}

func (h *userSrvHandler) DeleteUser(ctx context.Context, in *DeleteUserReq, out *DeleteUserResp) error {
	return h.UserSrvHandler.DeleteUser(ctx, in, out)
}

func (h *userSrvHandler) SelectUser(ctx context.Context, in *SelectUserReq, out *SelectUserResp) error {
	return h.UserSrvHandler.SelectUser(ctx, in, out)
}

func (h *userSrvHandler) UpdateUser(ctx context.Context, in *UpdateUserReq, out *UpdateUserResp) error {
	return h.UserSrvHandler.UpdateUser(ctx, in, out)
}
