// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: film-srv.proto

package film

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Film service

func NewFilmEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Film service

type FilmService interface {
	// 获取正在售票的影片
	HotPlayMovies(ctx context.Context, in *HotPlayMoviesReq, opts ...client.CallOption) (*HotPlayMoviesRep, error)
	// 电影详情
	MovieDetail(ctx context.Context, in *MovieDetailReq, opts ...client.CallOption) (*MovieDetailRep, error)
	// 获取导演与演员信息
	MovieCreditsWithTypes(ctx context.Context, in *MovieCreditsWithTypesReq, opts ...client.CallOption) (*MovieCreditsWithTypesRep, error)
	// 获取海报信息
	ImageAll(ctx context.Context, in *ImageAllReq, opts ...client.CallOption) (*ImageAllRep, error)
	// 正在热映的影片
	LocationMovies(ctx context.Context, in *LocationMoviesReq, opts ...client.CallOption) (*LocationMoviesRep, error)
	// 即将上映的影片
	MovieComingNew(ctx context.Context, in *MovieComingNewReq, opts ...client.CallOption) (*MovieComingNewRep, error)
	// 图片搜索
	Search(ctx context.Context, in *SearchReq, opts ...client.CallOption) (*SearchRep, error)
	// 根据影院id和时间获取正在销售的影片信息
	GetFilmsByCidADay(ctx context.Context, in *GetFilmsByCidADayReq, opts ...client.CallOption) (*GetFilmsByCidADayRsp, error)
}

type filmService struct {
	c    client.Client
	name string
}

func NewFilmService(name string, c client.Client) FilmService {
	return &filmService{
		c:    c,
		name: name,
	}
}

func (c *filmService) HotPlayMovies(ctx context.Context, in *HotPlayMoviesReq, opts ...client.CallOption) (*HotPlayMoviesRep, error) {
	req := c.c.NewRequest(c.name, "Film.HotPlayMovies", in)
	out := new(HotPlayMoviesRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmService) MovieDetail(ctx context.Context, in *MovieDetailReq, opts ...client.CallOption) (*MovieDetailRep, error) {
	req := c.c.NewRequest(c.name, "Film.MovieDetail", in)
	out := new(MovieDetailRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmService) MovieCreditsWithTypes(ctx context.Context, in *MovieCreditsWithTypesReq, opts ...client.CallOption) (*MovieCreditsWithTypesRep, error) {
	req := c.c.NewRequest(c.name, "Film.MovieCreditsWithTypes", in)
	out := new(MovieCreditsWithTypesRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmService) ImageAll(ctx context.Context, in *ImageAllReq, opts ...client.CallOption) (*ImageAllRep, error) {
	req := c.c.NewRequest(c.name, "Film.ImageAll", in)
	out := new(ImageAllRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmService) LocationMovies(ctx context.Context, in *LocationMoviesReq, opts ...client.CallOption) (*LocationMoviesRep, error) {
	req := c.c.NewRequest(c.name, "Film.LocationMovies", in)
	out := new(LocationMoviesRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmService) MovieComingNew(ctx context.Context, in *MovieComingNewReq, opts ...client.CallOption) (*MovieComingNewRep, error) {
	req := c.c.NewRequest(c.name, "Film.MovieComingNew", in)
	out := new(MovieComingNewRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmService) Search(ctx context.Context, in *SearchReq, opts ...client.CallOption) (*SearchRep, error) {
	req := c.c.NewRequest(c.name, "Film.Search", in)
	out := new(SearchRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmService) GetFilmsByCidADay(ctx context.Context, in *GetFilmsByCidADayReq, opts ...client.CallOption) (*GetFilmsByCidADayRsp, error) {
	req := c.c.NewRequest(c.name, "Film.GetFilmsByCidADay", in)
	out := new(GetFilmsByCidADayRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Film service

type FilmHandler interface {
	// 获取正在售票的影片
	HotPlayMovies(context.Context, *HotPlayMoviesReq, *HotPlayMoviesRep) error
	// 电影详情
	MovieDetail(context.Context, *MovieDetailReq, *MovieDetailRep) error
	// 获取导演与演员信息
	MovieCreditsWithTypes(context.Context, *MovieCreditsWithTypesReq, *MovieCreditsWithTypesRep) error
	// 获取海报信息
	ImageAll(context.Context, *ImageAllReq, *ImageAllRep) error
	// 正在热映的影片
	LocationMovies(context.Context, *LocationMoviesReq, *LocationMoviesRep) error
	// 即将上映的影片
	MovieComingNew(context.Context, *MovieComingNewReq, *MovieComingNewRep) error
	// 图片搜索
	Search(context.Context, *SearchReq, *SearchRep) error
	// 根据影院id和时间获取正在销售的影片信息
	GetFilmsByCidADay(context.Context, *GetFilmsByCidADayReq, *GetFilmsByCidADayRsp) error
}

func RegisterFilmHandler(s server.Server, hdlr FilmHandler, opts ...server.HandlerOption) error {
	type film interface {
		HotPlayMovies(ctx context.Context, in *HotPlayMoviesReq, out *HotPlayMoviesRep) error
		MovieDetail(ctx context.Context, in *MovieDetailReq, out *MovieDetailRep) error
		MovieCreditsWithTypes(ctx context.Context, in *MovieCreditsWithTypesReq, out *MovieCreditsWithTypesRep) error
		ImageAll(ctx context.Context, in *ImageAllReq, out *ImageAllRep) error
		LocationMovies(ctx context.Context, in *LocationMoviesReq, out *LocationMoviesRep) error
		MovieComingNew(ctx context.Context, in *MovieComingNewReq, out *MovieComingNewRep) error
		Search(ctx context.Context, in *SearchReq, out *SearchRep) error
		GetFilmsByCidADay(ctx context.Context, in *GetFilmsByCidADayReq, out *GetFilmsByCidADayRsp) error
	}
	type Film struct {
		film
	}
	h := &filmHandler{hdlr}
	return s.Handle(s.NewHandler(&Film{h}, opts...))
}

type filmHandler struct {
	FilmHandler
}

func (h *filmHandler) HotPlayMovies(ctx context.Context, in *HotPlayMoviesReq, out *HotPlayMoviesRep) error {
	return h.FilmHandler.HotPlayMovies(ctx, in, out)
}

func (h *filmHandler) MovieDetail(ctx context.Context, in *MovieDetailReq, out *MovieDetailRep) error {
	return h.FilmHandler.MovieDetail(ctx, in, out)
}

func (h *filmHandler) MovieCreditsWithTypes(ctx context.Context, in *MovieCreditsWithTypesReq, out *MovieCreditsWithTypesRep) error {
	return h.FilmHandler.MovieCreditsWithTypes(ctx, in, out)
}

func (h *filmHandler) ImageAll(ctx context.Context, in *ImageAllReq, out *ImageAllRep) error {
	return h.FilmHandler.ImageAll(ctx, in, out)
}

func (h *filmHandler) LocationMovies(ctx context.Context, in *LocationMoviesReq, out *LocationMoviesRep) error {
	return h.FilmHandler.LocationMovies(ctx, in, out)
}

func (h *filmHandler) MovieComingNew(ctx context.Context, in *MovieComingNewReq, out *MovieComingNewRep) error {
	return h.FilmHandler.MovieComingNew(ctx, in, out)
}

func (h *filmHandler) Search(ctx context.Context, in *SearchReq, out *SearchRep) error {
	return h.FilmHandler.Search(ctx, in, out)
}

func (h *filmHandler) GetFilmsByCidADay(ctx context.Context, in *GetFilmsByCidADayReq, out *GetFilmsByCidADayRsp) error {
	return h.FilmHandler.GetFilmsByCidADay(ctx, in, out)
}
