// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"module/internal/biz"
	"module/internal/conf"
	"module/internal/data"
	"module/internal/server"
	"module/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, consul *conf.Consul, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	moduleRepo := data.NewModuleRepo(dataData, logger)
	moduleUsecase := biz.NewModuleUsecase(moduleRepo, logger)
	moduleService := service.NewModuleService(moduleUsecase)
	grpcServer := server.NewGRPCServer(confServer, moduleService, logger)
	registry := server.NewRegistry(consul)
	app := newApp(logger, grpcServer, registry)
	return app, func() {
		cleanup()
	}, nil
}
