FROM registry.cn-hangzhou.aliyuncs.com/wcjs_docker/gobase:2.0.0
RUN mkdir -p /usr/local/gowork/src/wcjs
RUN cd /usr/local/gowork/src/wcjs && git clone git@git.chemm.com:backend/lib.git
CMD ["/bin/bash"]