// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/usersrv.proto

package usersrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Usersrv service

func NewUsersrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Usersrv service

type UsersrvService interface {
	InsertUser(ctx context.Context, in *InsertUserReq, opts ...client.CallOption) (*InsertUserRep, error)
	DeletetUser(ctx context.Context, in *DeletetUserReq, opts ...client.CallOption) (*DeletetUserRep, error)
	SelectUser(ctx context.Context, in *SelectUserReq, opts ...client.CallOption) (*SelectUserRep, error)
	UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...client.CallOption) (*UpdateUserRep, error)
}

type usersrvService struct {
	c    client.Client
	name string
}

func NewUsersrvService(name string, c client.Client) UsersrvService {
	return &usersrvService{
		c:    c,
		name: name,
	}
}

func (c *usersrvService) InsertUser(ctx context.Context, in *InsertUserReq, opts ...client.CallOption) (*InsertUserRep, error) {
	req := c.c.NewRequest(c.name, "Usersrv.InsertUser", in)
	out := new(InsertUserRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersrvService) DeletetUser(ctx context.Context, in *DeletetUserReq, opts ...client.CallOption) (*DeletetUserRep, error) {
	req := c.c.NewRequest(c.name, "Usersrv.DeletetUser", in)
	out := new(DeletetUserRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersrvService) SelectUser(ctx context.Context, in *SelectUserReq, opts ...client.CallOption) (*SelectUserRep, error) {
	req := c.c.NewRequest(c.name, "Usersrv.SelectUser", in)
	out := new(SelectUserRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersrvService) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...client.CallOption) (*UpdateUserRep, error) {
	req := c.c.NewRequest(c.name, "Usersrv.UpdateUser", in)
	out := new(UpdateUserRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Usersrv service

type UsersrvHandler interface {
	InsertUser(context.Context, *InsertUserReq, *InsertUserRep) error
	DeletetUser(context.Context, *DeletetUserReq, *DeletetUserRep) error
	SelectUser(context.Context, *SelectUserReq, *SelectUserRep) error
	UpdateUser(context.Context, *UpdateUserReq, *UpdateUserRep) error
}

func RegisterUsersrvHandler(s server.Server, hdlr UsersrvHandler, opts ...server.HandlerOption) error {
	type usersrv interface {
		InsertUser(ctx context.Context, in *InsertUserReq, out *InsertUserRep) error
		DeletetUser(ctx context.Context, in *DeletetUserReq, out *DeletetUserRep) error
		SelectUser(ctx context.Context, in *SelectUserReq, out *SelectUserRep) error
		UpdateUser(ctx context.Context, in *UpdateUserReq, out *UpdateUserRep) error
	}
	type Usersrv struct {
		usersrv
	}
	h := &usersrvHandler{hdlr}
	return s.Handle(s.NewHandler(&Usersrv{h}, opts...))
}

type usersrvHandler struct {
	UsersrvHandler
}

func (h *usersrvHandler) InsertUser(ctx context.Context, in *InsertUserReq, out *InsertUserRep) error {
	return h.UsersrvHandler.InsertUser(ctx, in, out)
}

func (h *usersrvHandler) DeletetUser(ctx context.Context, in *DeletetUserReq, out *DeletetUserRep) error {
	return h.UsersrvHandler.DeletetUser(ctx, in, out)
}

func (h *usersrvHandler) SelectUser(ctx context.Context, in *SelectUserReq, out *SelectUserRep) error {
	return h.UsersrvHandler.SelectUser(ctx, in, out)
}

func (h *usersrvHandler) UpdateUser(ctx context.Context, in *UpdateUserReq, out *UpdateUserRep) error {
	return h.UsersrvHandler.UpdateUser(ctx, in, out)
}
