// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type InfoReply struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	Created_at string `json:"created_at"`
}

type InfoReq struct {
	Id int64 `json:"id"`
}
