// Code generated by goctl. DO NOT EDIT.
// Source: demo.proto

package democlient

import (
	"context"

	"demo-rpc/types/demo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DemoRequest  = demo.DemoRequest
	DemoResponse = demo.DemoResponse

	Demo interface {
		// rpc方法
		GetID(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoResponse, error)
	}

	defaultDemo struct {
		cli zrpc.Client
	}
)

func NewDemo(cli zrpc.Client) Demo {
	return &defaultDemo{
		cli: cli,
	}
}

// rpc方法
func (m *defaultDemo) GetID(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoResponse, error) {
	client := demo.NewDemoClient(m.cli.Conn())
	return client.GetID(ctx, in, opts...)
}
