// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: order-srv.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WantTicketReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FilmId int64 `protobuf:"varint,2,opt,name=filmId,proto3" json:"filmId,omitempty"`
	Type   int64 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"` // 1为即将上映 2为正在热映 的电影
}

func (x *WantTicketReq) Reset() {
	*x = WantTicketReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WantTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantTicketReq) ProtoMessage() {}

func (x *WantTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantTicketReq.ProtoReflect.Descriptor instead.
func (*WantTicketReq) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{0}
}

func (x *WantTicketReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WantTicketReq) GetFilmId() int64 {
	if x != nil {
		return x.FilmId
	}
	return 0
}

func (x *WantTicketReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type WantTicketRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WantTicketRsp) Reset() {
	*x = WantTicketRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WantTicketRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantTicketRsp) ProtoMessage() {}

func (x *WantTicketRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantTicketRsp.ProtoReflect.Descriptor instead.
func (*WantTicketRsp) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{1}
}

type TicketReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FilmId    int64  `protobuf:"varint,2,opt,name=filmId,proto3" json:"filmId,omitempty"`
	MhId      int64  `protobuf:"varint,3,opt,name=mhId,proto3" json:"mhId,omitempty"`
	X         int64  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y         int64  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	StartTime string `protobuf:"bytes,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   string `protobuf:"bytes,7,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *TicketReq) Reset() {
	*x = TicketReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketReq) ProtoMessage() {}

func (x *TicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketReq.ProtoReflect.Descriptor instead.
func (*TicketReq) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{2}
}

func (x *TicketReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TicketReq) GetFilmId() int64 {
	if x != nil {
		return x.FilmId
	}
	return 0
}

func (x *TicketReq) GetMhId() int64 {
	if x != nil {
		return x.MhId
	}
	return 0
}

func (x *TicketReq) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TicketReq) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TicketReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TicketReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type TicketRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNumD int64 `protobuf:"varint,1,opt,name=orderNumD,proto3" json:"orderNumD,omitempty"`
}

func (x *TicketRsp) Reset() {
	*x = TicketRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketRsp) ProtoMessage() {}

func (x *TicketRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketRsp.ProtoReflect.Descriptor instead.
func (*TicketRsp) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{3}
}

func (x *TicketRsp) GetOrderNumD() int64 {
	if x != nil {
		return x.OrderNumD
	}
	return 0
}

type OrderData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNum   string `protobuf:"bytes,1,opt,name=orderNum,proto3" json:"orderNum,omitempty"`     // 订单编号
	OrderPrice string `protobuf:"bytes,2,opt,name=orderPrice,proto3" json:"orderPrice,omitempty"` // 订单价格
	CreateAt   string `protobuf:"bytes,3,opt,name=createAt,proto3" json:"createAt,omitempty"`     // 生成时间
	PayAt      string `protobuf:"bytes,4,opt,name=payAt,proto3" json:"payAt,omitempty"`           // 支付时间
	MhId       int64  `protobuf:"varint,5,opt,name=mhId,proto3" json:"mhId,omitempty"`            // 影厅编号
	UserId     int64  `protobuf:"varint,6,opt,name=userId,proto3" json:"userId,omitempty"`        // 用户编号
	MovieId    int64  `protobuf:"varint,7,opt,name=movieId,proto3" json:"movieId,omitempty"`      // 影片id
}

func (x *OrderData) Reset() {
	*x = OrderData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderData) ProtoMessage() {}

func (x *OrderData) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderData.ProtoReflect.Descriptor instead.
func (*OrderData) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{4}
}

func (x *OrderData) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

func (x *OrderData) GetOrderPrice() string {
	if x != nil {
		return x.OrderPrice
	}
	return ""
}

func (x *OrderData) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *OrderData) GetPayAt() string {
	if x != nil {
		return x.PayAt
	}
	return ""
}

func (x *OrderData) GetMhId() int64 {
	if x != nil {
		return x.MhId
	}
	return 0
}

func (x *OrderData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderData) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type MovieTicket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilmName  string `protobuf:"bytes,1,opt,name=filmName,proto3" json:"filmName,omitempty"`   // 影片名字
	StartTime string `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"` // 上映时间
	Cinema    string `protobuf:"bytes,3,opt,name=cinema,proto3" json:"cinema,omitempty"`       // 影院名字
	OrderNum  string `protobuf:"bytes,4,opt,name=orderNum,proto3" json:"orderNum,omitempty"`   // 订单编号
}

func (x *MovieTicket) Reset() {
	*x = MovieTicket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieTicket) ProtoMessage() {}

func (x *MovieTicket) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieTicket.ProtoReflect.Descriptor instead.
func (*MovieTicket) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{5}
}

func (x *MovieTicket) GetFilmName() string {
	if x != nil {
		return x.FilmName
	}
	return ""
}

func (x *MovieTicket) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *MovieTicket) GetCinema() string {
	if x != nil {
		return x.Cinema
	}
	return ""
}

func (x *MovieTicket) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

type LookOrdersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *LookOrdersReq) Reset() {
	*x = LookOrdersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookOrdersReq) ProtoMessage() {}

func (x *LookOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookOrdersReq.ProtoReflect.Descriptor instead.
func (*LookOrdersReq) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{6}
}

func (x *LookOrdersReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LookOrdersRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieTickets []*MovieTicket `protobuf:"bytes,1,rep,name=movieTickets,proto3" json:"movieTickets,omitempty"`
}

func (x *LookOrdersRsp) Reset() {
	*x = LookOrdersRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookOrdersRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookOrdersRsp) ProtoMessage() {}

func (x *LookOrdersRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookOrdersRsp.ProtoReflect.Descriptor instead.
func (*LookOrdersRsp) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{7}
}

func (x *LookOrdersRsp) GetMovieTickets() []*MovieTicket {
	if x != nil {
		return x.MovieTickets
	}
	return nil
}

type PayOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNum string `protobuf:"bytes,1,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	UserId   int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Phone    int64  `protobuf:"varint,3,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *PayOrderReq) Reset() {
	*x = PayOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderReq) ProtoMessage() {}

func (x *PayOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderReq.ProtoReflect.Descriptor instead.
func (*PayOrderReq) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{8}
}

func (x *PayOrderReq) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

func (x *PayOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayOrderReq) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

type PayOrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PayOrderRsp) Reset() {
	*x = PayOrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderRsp) ProtoMessage() {}

func (x *PayOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderRsp.ProtoReflect.Descriptor instead.
func (*PayOrderRsp) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{9}
}

type UndoOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId int64 `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
}

func (x *UndoOrderReq) Reset() {
	*x = UndoOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndoOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoOrderReq) ProtoMessage() {}

func (x *UndoOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoOrderReq.ProtoReflect.Descriptor instead.
func (*UndoOrderReq) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{10}
}

func (x *UndoOrderReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type UndoOrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UndoOrderRsp) Reset() {
	*x = UndoOrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndoOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoOrderRsp) ProtoMessage() {}

func (x *UndoOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoOrderRsp.ProtoReflect.Descriptor instead.
func (*UndoOrderRsp) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{11}
}

type GetOrderMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNum string `protobuf:"bytes,1,opt,name=orderNum,proto3" json:"orderNum,omitempty"` // 影片编号
	UserId   int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`    // 用户id
}

func (x *GetOrderMessageReq) Reset() {
	*x = GetOrderMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderMessageReq) ProtoMessage() {}

func (x *GetOrderMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderMessageReq.ProtoReflect.Descriptor instead.
func (*GetOrderMessageReq) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrderMessageReq) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

func (x *GetOrderMessageReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOrderMessageRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketDetail *TicketDetail `protobuf:"bytes,1,opt,name=ticketDetail,proto3" json:"ticketDetail,omitempty"`
}

func (x *GetOrderMessageRsp) Reset() {
	*x = GetOrderMessageRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderMessageRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderMessageRsp) ProtoMessage() {}

func (x *GetOrderMessageRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderMessageRsp.ProtoReflect.Descriptor instead.
func (*GetOrderMessageRsp) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrderMessageRsp) GetTicketDetail() *TicketDetail {
	if x != nil {
		return x.TicketDetail
	}
	return nil
}

type TicketDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilmName      string  `protobuf:"bytes,1,opt,name=filmName,proto3" json:"filmName,omitempty"`
	FilmImg       string  `protobuf:"bytes,2,opt,name=filmImg,proto3" json:"filmImg,omitempty"`
	StartTime     string  `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       string  `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	CinemaName    string  `protobuf:"bytes,5,opt,name=cinemaName,proto3" json:"cinemaName,omitempty"`
	MhName        string  `protobuf:"bytes,6,opt,name=mhName,proto3" json:"mhName,omitempty"`
	Seat          string  `protobuf:"bytes,7,opt,name=seat,proto3" json:"seat,omitempty"`
	OrderNum      string  `protobuf:"bytes,8,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	CinemaAddress string  `protobuf:"bytes,9,opt,name=cinemaAddress,proto3" json:"cinemaAddress,omitempty"`
	Price         float32 `protobuf:"fixed32,10,opt,name=price,proto3" json:"price,omitempty"`
	CreateAt      string  `protobuf:"bytes,11,opt,name=createAt,proto3" json:"createAt,omitempty"`
	Phone         int64   `protobuf:"varint,12,opt,name=phone,proto3" json:"phone,omitempty"`
	CinemaPhone   int64   `protobuf:"varint,13,opt,name=cinemaPhone,proto3" json:"cinemaPhone,omitempty"`
}

func (x *TicketDetail) Reset() {
	*x = TicketDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketDetail) ProtoMessage() {}

func (x *TicketDetail) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketDetail.ProtoReflect.Descriptor instead.
func (*TicketDetail) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{14}
}

func (x *TicketDetail) GetFilmName() string {
	if x != nil {
		return x.FilmName
	}
	return ""
}

func (x *TicketDetail) GetFilmImg() string {
	if x != nil {
		return x.FilmImg
	}
	return ""
}

func (x *TicketDetail) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TicketDetail) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *TicketDetail) GetCinemaName() string {
	if x != nil {
		return x.CinemaName
	}
	return ""
}

func (x *TicketDetail) GetMhName() string {
	if x != nil {
		return x.MhName
	}
	return ""
}

func (x *TicketDetail) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *TicketDetail) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

func (x *TicketDetail) GetCinemaAddress() string {
	if x != nil {
		return x.CinemaAddress
	}
	return ""
}

func (x *TicketDetail) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TicketDetail) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *TicketDetail) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

func (x *TicketDetail) GetCinemaPhone() int64 {
	if x != nil {
		return x.CinemaPhone
	}
	return 0
}

type LookAlreadyOrdersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *LookAlreadyOrdersReq) Reset() {
	*x = LookAlreadyOrdersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookAlreadyOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookAlreadyOrdersReq) ProtoMessage() {}

func (x *LookAlreadyOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookAlreadyOrdersReq.ProtoReflect.Descriptor instead.
func (*LookAlreadyOrdersReq) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{15}
}

func (x *LookAlreadyOrdersReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// messages:{"totalMovie":2,"oneNoComment":2,"movies":[{"filmImg":"http://img5.mtime.cn/mt/2017/10/23/101938.17733324_1280X720X2.jpg","filmName":"悟空传","time":"2017-07-13","director":"果子酱","actorNames":["彭于晏","欧豪"],"orderNum":"201701021003123"},{"filmImg":"http://img5.mtime.cn/mt/2017/10/23/101938.17733324_1280X720X2.jpg","filmName":"悟空传","time":"2017-07-13","director":"果子酱","actorNames":["彭于晏","欧豪"],"orderNum":"201701021003123"}]}
type LookAlreadyOrdersRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalMovie   int64           `protobuf:"varint,1,opt,name=totalMovie,proto3" json:"totalMovie,omitempty"`     // 看过的影片数量
	OneNoComment int64           `protobuf:"varint,2,opt,name=oneNoComment,proto3" json:"oneNoComment,omitempty"` // 还没有评价的影片数量
	Movies       []*AlreadyMovie `protobuf:"bytes,3,rep,name=movies,proto3" json:"movies,omitempty"`
}

func (x *LookAlreadyOrdersRsp) Reset() {
	*x = LookAlreadyOrdersRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookAlreadyOrdersRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookAlreadyOrdersRsp) ProtoMessage() {}

func (x *LookAlreadyOrdersRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookAlreadyOrdersRsp.ProtoReflect.Descriptor instead.
func (*LookAlreadyOrdersRsp) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{16}
}

func (x *LookAlreadyOrdersRsp) GetTotalMovie() int64 {
	if x != nil {
		return x.TotalMovie
	}
	return 0
}

func (x *LookAlreadyOrdersRsp) GetOneNoComment() int64 {
	if x != nil {
		return x.OneNoComment
	}
	return 0
}

func (x *LookAlreadyOrdersRsp) GetMovies() []*AlreadyMovie {
	if x != nil {
		return x.Movies
	}
	return nil
}

type AlreadyMovie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilmImg    string   `protobuf:"bytes,1,opt,name=filmImg,proto3" json:"filmImg,omitempty"`
	FilmName   string   `protobuf:"bytes,2,opt,name=filmName,proto3" json:"filmName,omitempty"`
	Time       string   `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Director   string   `protobuf:"bytes,4,opt,name=director,proto3" json:"director,omitempty"`
	ActorNames []string `protobuf:"bytes,5,rep,name=actorNames,proto3" json:"actorNames,omitempty"`
	OrderNum   string   `protobuf:"bytes,6,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
}

func (x *AlreadyMovie) Reset() {
	*x = AlreadyMovie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlreadyMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlreadyMovie) ProtoMessage() {}

func (x *AlreadyMovie) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlreadyMovie.ProtoReflect.Descriptor instead.
func (*AlreadyMovie) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{17}
}

func (x *AlreadyMovie) GetFilmImg() string {
	if x != nil {
		return x.FilmImg
	}
	return ""
}

func (x *AlreadyMovie) GetFilmName() string {
	if x != nil {
		return x.FilmName
	}
	return ""
}

func (x *AlreadyMovie) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *AlreadyMovie) GetDirector() string {
	if x != nil {
		return x.Director
	}
	return ""
}

func (x *AlreadyMovie) GetActorNames() []string {
	if x != nil {
		return x.ActorNames
	}
	return nil
}

func (x *AlreadyMovie) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

type OrderCommentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Score          int64  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	CommentContent string `protobuf:"bytes,3,opt,name=commentContent,proto3" json:"commentContent,omitempty"`
	OrderNum       string `protobuf:"bytes,4,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	MovieId        int64  `protobuf:"varint,5,opt,name=movieId,proto3" json:"movieId,omitempty"`
}

func (x *OrderCommentReq) Reset() {
	*x = OrderCommentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCommentReq) ProtoMessage() {}

func (x *OrderCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCommentReq.ProtoReflect.Descriptor instead.
func (*OrderCommentReq) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{18}
}

func (x *OrderCommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderCommentReq) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *OrderCommentReq) GetCommentContent() string {
	if x != nil {
		return x.CommentContent
	}
	return ""
}

func (x *OrderCommentReq) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

func (x *OrderCommentReq) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type OrderCommentRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderCommentRsp) Reset() {
	*x = OrderCommentRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_srv_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCommentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCommentRsp) ProtoMessage() {}

func (x *OrderCommentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_srv_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCommentRsp.ProtoReflect.Descriptor instead.
func (*OrderCommentRsp) Descriptor() ([]byte, []int) {
	return file_order_srv_proto_rawDescGZIP(), []int{19}
}

var File_order_srv_proto protoreflect.FileDescriptor

var file_order_srv_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2d, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x53, 0x0a, 0x0d, 0x57, 0x61, 0x6e, 0x74,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x0f, 0x0a,
	0x0d, 0x57, 0x61, 0x6e, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x73, 0x70, 0x22, 0xa3,
	0x01, 0x0a, 0x09, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x6d, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x68, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x68, 0x49, 0x64,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x09, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x73,
	0x70, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x44, 0x22,
	0xbf, 0x01, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x79, 0x41, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x79, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x68, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x68, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49,
	0x64, 0x22, 0x7b, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69,
	0x6e, 0x65, 0x6d, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x6e, 0x65,
	0x6d, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x27,
	0x0a, 0x0d, 0x4c, 0x6f, 0x6f, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x0d, 0x4c, 0x6f, 0x6f, 0x6b, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0c, 0x6d, 0x6f, 0x76, 0x69,
	0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x0c, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73,
	0x22, 0x57, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x61, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x28, 0x0a, 0x0c, 0x55, 0x6e, 0x64, 0x6f,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x55, 0x6e, 0x64, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x73, 0x70, 0x22, 0x48, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x73, 0x70, 0x12, 0x37, 0x0a, 0x0c, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0c, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0xf4, 0x02, 0x0a, 0x0c,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x6d,
	0x49, 0x6d, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x6d, 0x49,
	0x6d, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69,
	0x6e, 0x65, 0x6d, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x68,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x68, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e,
	0x75, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e,
	0x75, 0x6d, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x69, 0x6e, 0x65, 0x6d,
	0x61, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x22, 0x2e, 0x0a, 0x14, 0x4c, 0x6f, 0x6f, 0x6b, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64,
	0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x87, 0x01, 0x0a, 0x14, 0x4c, 0x6f, 0x6f, 0x6b, 0x41, 0x6c, 0x72, 0x65, 0x61,
	0x64, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6f,
	0x6e, 0x65, 0x4e, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x6f, 0x6e, 0x65, 0x4e, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x2b, 0x0a, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x52, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x22, 0xb0, 0x01, 0x0a,
	0x0c, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x66, 0x69, 0x6c, 0x6d, 0x49, 0x6d, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x66, 0x69, 0x6c, 0x6d, 0x49, 0x6d, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x22,
	0x9d, 0x01, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x22,
	0x11, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x73, 0x70, 0x32, 0xfc, 0x03, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x0a,
	0x57, 0x61, 0x6e, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x14, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x57, 0x61, 0x6e, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x57, 0x61, 0x6e, 0x74, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x06, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x10, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x08, 0x50, 0x61, 0x79, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x37,
	0x0a, 0x09, 0x55, 0x6e, 0x64, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x64, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x64, 0x6f, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0a, 0x4c, 0x6f, 0x6f, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x12, 0x14, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4c,
	0x6f, 0x6f, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4f,
	0x0a, 0x11, 0x4c, 0x6f, 0x6f, 0x6b, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x12, 0x1b, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b,
	0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x1b, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x41, 0x6c, 0x72,
	0x65, 0x61, 0x64, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x40, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x16, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x22,
	0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_srv_proto_rawDescOnce sync.Once
	file_order_srv_proto_rawDescData = file_order_srv_proto_rawDesc
)

func file_order_srv_proto_rawDescGZIP() []byte {
	file_order_srv_proto_rawDescOnce.Do(func() {
		file_order_srv_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_srv_proto_rawDescData)
	})
	return file_order_srv_proto_rawDescData
}

var file_order_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_order_srv_proto_goTypes = []interface{}{
	(*WantTicketReq)(nil),        // 0: order.WantTicketReq
	(*WantTicketRsp)(nil),        // 1: order.WantTicketRsp
	(*TicketReq)(nil),            // 2: order.TicketReq
	(*TicketRsp)(nil),            // 3: order.TicketRsp
	(*OrderData)(nil),            // 4: order.OrderData
	(*MovieTicket)(nil),          // 5: order.MovieTicket
	(*LookOrdersReq)(nil),        // 6: order.LookOrdersReq
	(*LookOrdersRsp)(nil),        // 7: order.LookOrdersRsp
	(*PayOrderReq)(nil),          // 8: order.PayOrderReq
	(*PayOrderRsp)(nil),          // 9: order.PayOrderRsp
	(*UndoOrderReq)(nil),         // 10: order.UndoOrderReq
	(*UndoOrderRsp)(nil),         // 11: order.UndoOrderRsp
	(*GetOrderMessageReq)(nil),   // 12: order.GetOrderMessageReq
	(*GetOrderMessageRsp)(nil),   // 13: order.GetOrderMessageRsp
	(*TicketDetail)(nil),         // 14: order.TicketDetail
	(*LookAlreadyOrdersReq)(nil), // 15: order.LookAlreadyOrdersReq
	(*LookAlreadyOrdersRsp)(nil), // 16: order.LookAlreadyOrdersRsp
	(*AlreadyMovie)(nil),         // 17: order.AlreadyMovie
	(*OrderCommentReq)(nil),      // 18: order.OrderCommentReq
	(*OrderCommentRsp)(nil),      // 19: order.OrderCommentRsp
}
var file_order_srv_proto_depIdxs = []int32{
	5,  // 0: order.LookOrdersRsp.movieTickets:type_name -> order.MovieTicket
	14, // 1: order.GetOrderMessageRsp.ticketDetail:type_name -> order.TicketDetail
	17, // 2: order.LookAlreadyOrdersRsp.movies:type_name -> order.AlreadyMovie
	0,  // 3: order.Order.WantTicket:input_type -> order.WantTicketReq
	2,  // 4: order.Order.Ticket:input_type -> order.TicketReq
	8,  // 5: order.Order.PayOrder:input_type -> order.PayOrderReq
	10, // 6: order.Order.UndoOrder:input_type -> order.UndoOrderReq
	12, // 7: order.Order.GetOrderMessage:input_type -> order.GetOrderMessageReq
	6,  // 8: order.Order.LookOrders:input_type -> order.LookOrdersReq
	15, // 9: order.Order.LookAlreadyOrders:input_type -> order.LookAlreadyOrdersReq
	18, // 10: order.Order.OrderComment:input_type -> order.OrderCommentReq
	1,  // 11: order.Order.WantTicket:output_type -> order.WantTicketRsp
	3,  // 12: order.Order.Ticket:output_type -> order.TicketRsp
	9,  // 13: order.Order.PayOrder:output_type -> order.PayOrderRsp
	11, // 14: order.Order.UndoOrder:output_type -> order.UndoOrderRsp
	13, // 15: order.Order.GetOrderMessage:output_type -> order.GetOrderMessageRsp
	7,  // 16: order.Order.LookOrders:output_type -> order.LookOrdersRsp
	16, // 17: order.Order.LookAlreadyOrders:output_type -> order.LookAlreadyOrdersRsp
	19, // 18: order.Order.OrderComment:output_type -> order.OrderCommentRsp
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_order_srv_proto_init() }
func file_order_srv_proto_init() {
	if File_order_srv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_srv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WantTicketReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WantTicketRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieTicket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookOrdersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookOrdersRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayOrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UndoOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UndoOrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderMessageRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookAlreadyOrdersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookAlreadyOrdersRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlreadyMovie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCommentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_srv_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCommentRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_srv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_srv_proto_goTypes,
		DependencyIndexes: file_order_srv_proto_depIdxs,
		MessageInfos:      file_order_srv_proto_msgTypes,
	}.Build()
	File_order_srv_proto = out.File
	file_order_srv_proto_rawDesc = nil
	file_order_srv_proto_goTypes = nil
	file_order_srv_proto_depIdxs = nil
}
